### ISSUE TITLE
No onChange is called when user minimizes the browser or switches to another app in IOS

### ISSUE THREAD

**Issue by lukephills** [bendrucker/document-visibility#1]
Hi thanks for this module. 

It works perfectly for switching tabs and minimizing the browser on desktop and android. However, in iOS when a user minimizes the browser (using a gesture) or switches to another app the visibility onChange isn't called. 

Is there any way to catch this event?

**Comment by bendrucker** [comment]
Doubt it. This is just a wrapper for the browser API. It's up to iOS to decide how to implement it.

**Comment by bendrucker** [comment]
iOS does seem to have `pagehide` and `pageshow` events, not sure if they're the right thing here. I can give it a try.

**Comment by lukephills** [comment]
Cool, thanks it looks like pageshow/hide will work. Note though that pagehide only gets executed when the app 'wakes up'. Damn iOS!
