### ISSUE TITLE
Can this package be babelified?

### ISSUE THREAD

**Issue by binarykitchen** [bendrucker/document-visibility#2]
In https://github.com/babel/babelify/issues/239 I am encountering difficulties to ES6-transform your package to ES5. Wondering if you ever managed it to work with `import Visibility from 'document-visibility'`?

Just have a guess, having `module.exports = Visibility` early at top of the file might confuse bundlers, I don't know?

**Comment by bendrucker** [comment]
The code is perfectly valid, no ideas tbh

**Comment by bendrucker** [comment]
Just to clarify, everything here is valid JS and all ES5. I'm not really sure where to start with your babel issue but I'm not doing anything unusual here.

**Comment by binarykitchen** [comment]
have you ever successfully browserified your package along with other ES6 modules altogether?
